
/**   
 *  Componentes do grupo
 *  Carolina de Lima Silva - 561397
 *  Jorge Allan de Castro Oliveira - 559855
 *  Ricardo Xavier Sena - 481694
 * 
 */

public enum TokenEnum {
  // An enumeration of all tokens in the language
  ID, VALUE, CONST, FINAL, INT, CHAR, BOOLEAN, IF, FOR, TRUE, FALSE, ELSE, AND, OR, NOT, THEN, READLN, WRITE, WRITELN,
  MAIN, ATTRIBUTION, EQUAL, OPEN_PARENTHESES, CLOSE_PARENTHESES, LESS_THAN, GREATER_THAN, NOT_EQUAL, GREATER_OR_EQUAL,
  LESS_OR_EQUAL, COMMA, PLUS, MINUS, MULTIPLY, DIVIDE, SEMICOLON, OPEN_BRACES, CLOSE_BRACES, PERCENTAGE, OPEN_BRACKETS,
  CLOSE_BRACKETS
}